### ISSUE TITLE
Footer/Navigation

### ISSUE THREAD

**Issue by suademre** [suademre/capstone-projekt#17]
As a user, i want to see footer menu

## Description
![image](https://user-images.githubusercontent.com/56043460/137460060-f2b7bf6f-8590-4275-b997-f207dbfa8fad.png)

## Acceptance Criteria
- [ ] i should to see Footer menu. 
- [ ]  When user click Favourite button, user should to go to favourite page. 

## Tasks
- [ ] Create feature branch
- [ ] Create Footer Component
- [ ] Write function
- [ ] Add router
- [ ] Add style
