### ISSUE TITLE
Favourite button&Favourite Page

### ISSUE THREAD

**Issue by suademre** [suademre/capstone-projekt#19]
As a user, i want to select favorite and see in the favourite page

## Description
![image](https://user-images.githubusercontent.com/56043460/137763239-4df57466-6f1f-40d5-8b8a-e9d34d39111e.png)

## Acceptance Criteria
- [ ] The icon will change when the user presses the button.
- [ ] When user click to favourite Button, user should be able to go to Favourite Page
- [ ] User can see the Products.

## Tasks
- [ ] Create feature branch
- [ ] Create Favourite Page Component
- [ ] Write functions
- [ ] Add button icons
- [ ] Update State
- [ ] Write test
- [ ] Add style
