### ISSUE TITLE
Completion of deficiencies

### ISSUE THREAD

**Issue by suademre** [suademre/capstone-projekt#26]
## Value Statement
As a User, i want to only sees the image and header on the homepage. 
If there is no product on the cart page and favorite page, i want to see `you do not have a product on the...`

## Acceptance Criteria
- [ ] There is only one image and header on the homepage
- [ ] If there is no product on the cart page and favorite page, write `you do not have a product on the...`
- [ ] make the styles a little more beautiful

## Tasks
- [ ] Create feature branch
- [ ] Create HomePage Component
- [ ] Add styles
