### ISSUE TITLE
[US-3] Products Detail

### ISSUE THREAD

**Issue by suademre** [suademre/capstone-projekt#5]
## Value Statement ( User Story)
As a user i want to see more Details for Products

## Description
![image](https://user-images.githubusercontent.com/56043460/138703453-cb8c18fa-6032-48f9-aa99-f8242dc501f2.png)

## Acceptance Criteria
- [ ] Only 1 product should have information.
- [ ] Products in Categories have Link, User go to "/category/${Product name}"

## Tasks
- [ ] Create feature branch
- [ ] Create Component
- [ ] Add Component to Category.js
- [ ]  Add Styling

## Complexity
low
