### ISSUE TITLE
[US-0] Menu

### ISSUE THREAD

**Issue by suademre** [suademre/capstone-projekt#6]
## Value Statement
As a user I want to be able to open a navigation menu via a button and closed to navigation menu.

## Description
![image](https://user-images.githubusercontent.com/56043460/136438327-b51641e6-3311-48dd-93ae-685164b40a5a.png)

## Acceptance Criteria
- [x] The menu should be indicated by an appropriate icon.
- [x] The menu icon should be at the top left in page.
- [x] The button should open a navigation menu and closed navigation menu

## Tasks
- [x] Create feature branch
- [x] Build component
- [x] write test for button
- [x] Add Styles

## Complexity
low
