### ISSUE TITLE
Add Sort in Category Page

### ISSUE THREAD

**Issue by suademre** [suademre/capstone-projekt#7]
As a user I want to sort products by price.

## Description
![image](https://user-images.githubusercontent.com/56043460/137931688-baa3521c-d855-470f-aa5d-2bccf1c25d0a.png)

## Acceptance Criteria
- [ ]  User should be able to sort thelist of Products by price.
- [ ]  Pressing the sort key opens another window.

## Tasks
- [ ] Create feature branch
- [ ] Write the required function to sort
- [ ] Add useState
- [ ] Add toggle to sidebar
- [ ] Add style
