### ISSUE TITLE
Favorite button in Category Page

### ISSUE THREAD

**Issue by suademre** [suademre/capstone-projekt#9]
As a user, i want to select favorite 

## Description
![image](https://user-images.githubusercontent.com/56043460/136556288-482c8f0f-ab3c-4448-9b56-351d8908f76f.png)

## Acceptance Criteria
- [ ] There will be two different icons. But only 1 will appear. The icon will change when the user presses the button.

## Tasks
- [ ] Create feature branch
- [ ] Write functions
- [ ] add to Component
- [ ] add useState
- [ ] add style
